project:
  type: website

website:
  title: "My Explorations With LLMs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lazyexcuseforausername
      - icon: linkedin
        href: https://www.linkedin.com/in/elenikan/
format:
  html:
    theme: minty
    css: styles.css

execute:
  freeze: auto


